version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: purehealthdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./purehealthdb.sql:/docker-entrypoint-initdb.d/purehealthdb.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    external: true