name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json, libxml, zip
          coverage: none

      - name: Install Composer
        uses: php-actions/composer@v6
        with:
          php_version: '8.0'
          version: latest

      - name: Set permissions
        run: sudo chown -R $USER:$USER .

      - name: Install dependencies
        run: sudo composer install

      - name: Create .env file
        run: |
          cat > .env << EOF
          APP_NAME=Laravel
          APP_ENV=local
          APP_KEY=base64:Z6oxiseWUZwQga5bmF1j9wEFLW4mqPpaYCycNK74Gao=
          APP_DEBUG=true
          APP_URL=https://purehealthtt.zoneitshop.com

          LOG_CHANNEL=stack
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=debug

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          BROADCAST_DRIVER=log
          CACHE_DRIVER=file
          FILESYSTEM_DISK=local
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120

          MEMCACHED_HOST=127.0.0.1

          REDIS_HOST=127.0.0.1
          REDIS_PASSWORD=null
          REDIS_PORT=6379

          MAIL_MAILER=smtp
          MAIL_HOST=smtp.gmail.com
          MAIL_PORT=587
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          MAIL_ENCRYPTION=tls
          MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}
          MAIL_FROM_NAME="PureHealthTT"

          AWS_ACCESS_KEY_ID=
          AWS_SECRET_ACCESS_KEY=
          AWS_DEFAULT_REGION=us-east-1
          AWS_BUCKET=
          AWS_USE_PATH_STYLE_ENDPOINT=false

          PUSHER_APP_ID=
          PUSHER_APP_KEY=
          PUSHER_APP_SECRET=
          PUSHER_HOST=
          PUSHER_PORT=443
          PUSHER_SCHEME=https
          PUSHER_APP_CLUSTER=mt1

          VITE_PUSHER_APP_KEY=${PUSHER_APP_KEY}
          VITE_PUSHER_HOST=${PUSHER_HOST}
          VITE_PUSHER_PORT=${PUSHER_PORT}
          VITE_PUSHER_SCHEME=${PUSHER_SCHEME}
          VITE_PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
          EOF
          cat .env

      - name: Create .htaccess file
        run: |
          echo "RewriteEngine On" >> .htaccess
          echo "RewriteRule ^(.*)$ public/$1 [L]" >> .htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-d" >> .htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-f" >> .htaccess
          echo "RewriteRule ^ public/index.php [L]" >> .htaccess

      - name: Create link public/storage
        run: php artisan storage:link

      - name: Copy to hosting
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./*"
          target: "~/public_html"
          rm: false
          overwrite: true
